#!/bin/sh
./configure \
    --disable-demuxers \
    --disable-ffserver \
    --disable-bsfs \
    --disable-parsers \
    --disable-protocols \
    --disable-muxers \
    --disable-decoders \
    --disable-encoders \
    --disable-ffmpeg \
    --disable-ffplay \
    --enable-encoder=mjpeg \
    --enable-decoder=mjpeg \
    --enable-encoder=rawvideo \
    --enable-muxer=mjpeg \
    --enable-demuxer=mjpeg \
    --enable-parser=mjpeg \
    --enable-decoder=rawvideo\
    --enable-demuxer=yuv4mpegpipe\
    --enable-muxer=yuv4mpegpipe\
    --enable-demuxer=rawvideo\
    --enable-muxer=rawvideo\
    --enable-protocol=file \
    --enable-pthreads \
    --disable-static \
    --enable-shared \
    --enable-gpl \
    --disable-stripping \
    "$@"
